### ISSUE TITLE
add auto ticket - daily amount of internet access time

### ISSUE THREAD

**Issue by uzi18** [k-szuster/luci-access-control-package#1]

**Comment by ravikjab** [comment]
Witam,
Czy możliwe było by aby 'bilety' dostępu do internety były wydawane automatycznie po zalogowaniu się danego urzytkownika ?

**Comment by k-szuster** [comment]
Raczej nie. Trzebaby użyć zupełnie innego mechanzmu, czyli napizać całkiem nowy program. Może coś takiego już istnieje?

**Comment by uzi18** [comment]
Gdyby dodać do crona test czy ilość danych do hosta rośnie ... To temat
jest już w 1/2 rozwiazany. Wystarczy wtedy uruchomić odliczanie.
Mogę spróbować to zrobić ale nie wiem czy będę umiał to przepisać na lua
dla spójności pluginu.

10.11.2016 8:07 PM "Krzysztof Szuster" notifications@github.com
napisał(a):
